version: '3.8'
services:
  api:
    container_name: api-container
    restart: unless-stopped
    image: compose-api-prod:1.0.0
    build:
      context: server
      target: production
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - shared-network
    depends_on:
      - mongo
  client:
    container_name: client-container
    restart: unless-stopped
    image: compose-client-prod:1.0.0
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
  mongo:
    container_name: mongo-backend
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - shared-network
    volumes:
      - ./apiDB:/data/db

networks:
  shared-network:
volumes:
  apiDB:
